# Generated by Django 5.1.1 on 2024-09-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vysota', '0003_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id'], 'verbose_name': 'Заказчики', 'verbose_name_plural': 'Заказчики'},
        ),
    ]
