# Generated by Django 5.1.1 on 2024-09-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vysota', '0004_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
